// Generated by `npm run types` after D1/R2 IDs are set in wrangler.jsonc.
// Placeholder bindings for local TypeScript until wrangler types runs.

interface Env {
  DB: D1Database;
  RENDERS: R2Bucket;
  ASSETS: Fetcher;
}
